name: Build, test, and push Halloween Docker image

on:
  push:
    branches:
      - "main"

jobs:
  build-test-and-push:
    runs-on: label-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image name
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/halloween-httpd" >> $GITHUB_ENV

      # REMOVED: Set permissions for Docker socket step

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Run container for test
        run: |
          docker run -d --name halloween-test -p 8080:80 $IMAGE_NAME:latest
          docker stop halloween-test
          docker rm halloween-test

      - name: List Docker containers
        run: docker ps -a

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push image to Docker Hub
        run: docker push $IMAGE_NAME:latest