name: Build, test, and push Halloween Docker image

on:
  push:
    branches:  "main" 
  
jobs:
  build-test-and-push:
    runs-on: label-1

    steps:
      # 1) Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set an IMAGE_NAME env variable like: rosinebelle/halloween-httpd
      - name: Set image name
       run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/halloween-httpd" >> $GITHUB_ENV

      # 3) Build the Docker image from your Dockerfile
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      # 4) Run the container to make sure it starts and serves HTTP
      - name: Run container for test
        run: |
          # Start the container in the background, map port 8080 on runner -> 80 in container
          docker run -d --name halloween-test -p 8080:80 $IMAGE_NAME:latest

          # Stop and remove the test container
          docker stop halloween-test
          docker rm halloween-test

      # 5) Log in to Docker Hub using your secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 6) Push the image to Docker Hub
      - name: Push image to Docker Hub
        run: docker push $IMAGE_NAME:latest

